// Generated by https://quicktype.io

export interface CategoryidResponse {
  results: Category;
}

export interface Category {
  id: string;
  name: string;
  description: string;
  created_at: string;
  updated_at: string;
}
