// Generated by https://quicktype.io

export interface EventResponse {
  results: Results;
}

export interface Results {
  count: number;
  totalPages: number;
  currentPage: number;
  results: Event[];
}

export interface Event {
  id: string;
  profile_id: string;
  publication_type_id: string;
  title: string;
  description: string;
  content: string;
  picture: null;
  city_id: string;
  image_url: null;
  created_at: string;
  updated_at: string;
  votes_count: number;
}
