// Generated by https://quicktype.io

export interface UserIdResponse {
  results: userId;
}

export interface userId {
  id: string;
  first_name: string;
  last_name: string;
  email: string;
  username: string;
}
